services:
  - type: web
    name: greenlink
    env: docker
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/greenlink-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: greenlink-db
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: greenlink-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: greenlink-db
          property: password
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1

databases:
  - name: greenlink-db
    plan: free
    databaseName: glink
    ipAllowList: [] 